name: Trigger Site Deploy
on:
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:
jobs:
  trigger:
    name: Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run build command
      run: yarn build
    - name: Trigger
      uses: netlify/actions/cli@master
      with:
        args: deploy --prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
