name: Trigger Site Deploy
on:
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:
jobs:
  trigger:
    name: Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Trigger
      uses: netlify/actions/build@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
